package net.minecraft.util.datafix;
import net.minecraft.block.BlockJukebox;
import net.minecraft.entity.Entity;
import net.minecraft.entity.boss.EntityDragon;
import net.minecraft.entity.boss.EntityWither;
import net.minecraft.entity.item.EntityArmorStand;
import net.minecraft.entity.item.EntityEnderPearl;
import net.minecraft.entity.item.EntityExpBottle;
import net.minecraft.entity.item.EntityFallingBlock;
import net.minecraft.entity.item.EntityFireworkRocket;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.item.EntityItemFrame;
import net.minecraft.entity.item.EntityMinecartChest;
import net.minecraft.entity.item.EntityMinecartCommandBlock;
import net.minecraft.entity.item.EntityMinecartEmpty;
import net.minecraft.entity.item.EntityMinecartFurnace;
import net.minecraft.entity.item.EntityMinecartHopper;
import net.minecraft.entity.item.EntityMinecartMobSpawner;
import net.minecraft.entity.item.EntityMinecartTNT;
import net.minecraft.entity.monster.EntityBlaze;
import net.minecraft.entity.monster.EntityCaveSpider;
import net.minecraft.entity.monster.EntityCreeper;
import net.minecraft.entity.monster.EntityElderGuardian;
import net.minecraft.entity.monster.EntityEnderman;
import net.minecraft.entity.monster.EntityEndermite;
import net.minecraft.entity.monster.EntityEvoker;
import net.minecraft.entity.monster.EntityGhast;
import net.minecraft.entity.monster.EntityGiantZombie;
import net.minecraft.entity.monster.EntityGuardian;
import net.minecraft.entity.monster.EntityHusk;
import net.minecraft.entity.monster.EntityIronGolem;
import net.minecraft.entity.monster.EntityMagmaCube;
import net.minecraft.entity.monster.EntityPigZombie;
import net.minecraft.entity.monster.EntityShulker;
import net.minecraft.entity.monster.EntitySilverfish;
import net.minecraft.entity.monster.EntitySkeleton;
import net.minecraft.entity.monster.EntitySlime;
import net.minecraft.entity.monster.EntitySnowman;
import net.minecraft.entity.monster.EntitySpider;
import net.minecraft.entity.monster.EntityStray;
import net.minecraft.entity.monster.EntityVex;
import net.minecraft.entity.monster.EntityVindicator;
import net.minecraft.entity.monster.EntityWitch;
import net.minecraft.entity.monster.EntityWitherSkeleton;
import net.minecraft.entity.monster.EntityZombie;
import net.minecraft.entity.monster.EntityZombieVillager;
import net.minecraft.entity.passive.EntityBat;
import net.minecraft.entity.passive.EntityChicken;
import net.minecraft.entity.passive.EntityCow;
import net.minecraft.entity.passive.EntityDonkey;
import net.minecraft.entity.passive.EntityHorse;
import net.minecraft.entity.passive.EntityMooshroom;
import net.minecraft.entity.passive.EntityMule;
import net.minecraft.entity.passive.EntityOcelot;
import net.minecraft.entity.passive.EntityPig;
import net.minecraft.entity.passive.EntityRabbit;
import net.minecraft.entity.passive.EntitySheep;
import net.minecraft.entity.passive.EntitySkeletonHorse;
import net.minecraft.entity.passive.EntitySquid;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.entity.passive.EntityWolf;
import net.minecraft.entity.passive.EntityZombieHorse;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.projectile.EntityArrow;
import net.minecraft.entity.projectile.EntityDragonFireball;
import net.minecraft.entity.projectile.EntityEgg;
import net.minecraft.entity.projectile.EntityLargeFireball;
import net.minecraft.entity.projectile.EntityPotion;
import net.minecraft.entity.projectile.EntitySmallFireball;
import net.minecraft.entity.projectile.EntitySnowball;
import net.minecraft.entity.projectile.EntitySpectralArrow;
import net.minecraft.entity.projectile.EntityTippedArrow;
import net.minecraft.entity.projectile.EntityWitherSkull;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import net.minecraft.tileentity.TileEntityBrewingStand;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.tileentity.TileEntityDispenser;
import net.minecraft.tileentity.TileEntityDropper;
import net.minecraft.tileentity.TileEntityFlowerPot;
import net.minecraft.tileentity.TileEntityFurnace;
import net.minecraft.tileentity.TileEntityHopper;
import net.minecraft.tileentity.TileEntityMobSpawner;
import net.minecraft.tileentity.TileEntityPiston;
import net.minecraft.tileentity.TileEntityShulkerBox;
import net.minecraft.util.datafix.fixes.AddBedTileEntity;
import net.minecraft.util.datafix.fixes.ArmorStandSilent;
import net.minecraft.util.datafix.fixes.BannerItemColor;
import net.minecraft.util.datafix.fixes.BedItemColor;
import net.minecraft.util.datafix.fixes.BookPagesStrictJSON;
import net.minecraft.util.datafix.fixes.CookedFishIDTypo;
import net.minecraft.util.datafix.fixes.ElderGuardianSplit;
import net.minecraft.util.datafix.fixes.EntityArmorAndHeld;
import net.minecraft.util.datafix.fixes.EntityHealth;
import net.minecraft.util.datafix.fixes.EntityId;
import net.minecraft.util.datafix.fixes.ForceVBOOn;
import net.minecraft.util.datafix.fixes.HorseSaddle;
import net.minecraft.util.datafix.fixes.HorseSplit;
import net.minecraft.util.datafix.fixes.ItemIntIDToString;
import net.minecraft.util.datafix.fixes.MinecartEntityTypes;
import net.minecraft.util.datafix.fixes.OptionsLowerCaseLanguage;
import net.minecraft.util.datafix.fixes.PaintingDirection;
import net.minecraft.util.datafix.fixes.PotionItems;
import net.minecraft.util.datafix.fixes.PotionWater;
import net.minecraft.util.datafix.fixes.RedundantChanceTags;
import net.minecraft.util.datafix.fixes.RidingToPassengers;
import net.minecraft.util.datafix.fixes.ShulkerBoxEntityColor;
import net.minecraft.util.datafix.fixes.ShulkerBoxItemColor;
import net.minecraft.util.datafix.fixes.ShulkerBoxTileColor;
import net.minecraft.util.datafix.fixes.SignStrictJSON;
import net.minecraft.util.datafix.fixes.SkeletonSplit;
import net.minecraft.util.datafix.fixes.SpawnEggNames;
import net.minecraft.util.datafix.fixes.SpawnerEntityTypes;
import net.minecraft.util.datafix.fixes.StringToUUID;
import net.minecraft.util.datafix.fixes.TileEntityId;
import net.minecraft.util.datafix.fixes.TotemItemRename;
import net.minecraft.util.datafix.fixes.ZombieProfToType;
import net.minecraft.util.datafix.fixes.ZombieSplit;
import net.minecraft.world.chunk.storage.AnvilChunkLoader;
import net.minecraft.world.gen.structure.template.Template;
import net.minecraft.world.storage.WorldInfo;


public class DataFixesManager {

    private static void func_188276_a(DataFixer dataconvertermanager) {
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new EntityArmorAndHeld()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.BLOCK_ENTITY, (IFixableData) (new SignStrictJSON()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new ItemIntIDToString()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new PotionItems()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new SpawnEggNames()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new MinecartEntityTypes()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.BLOCK_ENTITY, (IFixableData) (new SpawnerEntityTypes()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new StringToUUID()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new EntityHealth()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new HorseSaddle()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new PaintingDirection()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new RedundantChanceTags()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new RidingToPassengers()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new ArmorStandSilent()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new BookPagesStrictJSON()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new CookedFishIDTypo()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new ZombieProfToType()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.OPTIONS, (IFixableData) (new ForceVBOOn()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new ElderGuardianSplit()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new SkeletonSplit()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new ZombieSplit()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new HorseSplit()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.BLOCK_ENTITY, (IFixableData) (new TileEntityId()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new EntityId()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new BannerItemColor()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new PotionWater()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ENTITY, (IFixableData) (new ShulkerBoxEntityColor()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new ShulkerBoxItemColor()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.BLOCK_ENTITY, (IFixableData) (new ShulkerBoxTileColor()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.OPTIONS, (IFixableData) (new OptionsLowerCaseLanguage()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new TotemItemRename()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.CHUNK, (IFixableData) (new AddBedTileEntity()));
        dataconvertermanager.func_188256_a((IFixType) FixTypes.ITEM_INSTANCE, (IFixableData) (new BedItemColor()));
    }

    public static DataFixer func_188279_a() {
        DataFixer dataconvertermanager = new DataFixer(1343);

        WorldInfo.func_189967_a(dataconvertermanager);
        EntityPlayerMP.func_191522_a(dataconvertermanager);
        EntityPlayer.func_189806_a(dataconvertermanager);
        AnvilChunkLoader.func_189889_a(dataconvertermanager);
        ItemStack.func_189868_a(dataconvertermanager);
        Template.func_191158_a(dataconvertermanager);
        Entity.func_190533_a(dataconvertermanager);
        EntityArmorStand.func_189805_a(dataconvertermanager);
        EntityArrow.func_189658_a(dataconvertermanager);
        EntityBat.func_189754_b(dataconvertermanager);
        EntityBlaze.func_189761_b(dataconvertermanager);
        EntityCaveSpider.func_189775_b(dataconvertermanager);
        EntityChicken.func_189789_b(dataconvertermanager);
        EntityCow.func_189790_b(dataconvertermanager);
        EntityCreeper.func_189762_b(dataconvertermanager);
        EntityDonkey.func_190699_b(dataconvertermanager);
        EntityDragonFireball.func_189747_a(dataconvertermanager);
        EntityElderGuardian.func_190768_b(dataconvertermanager);
        EntityDragon.func_189755_b(dataconvertermanager);
        EntityEnderman.func_189763_b(dataconvertermanager);
        EntityEndermite.func_189764_b(dataconvertermanager);
        EntityEvoker.func_190759_b(dataconvertermanager);
        EntityFallingBlock.func_189741_a(dataconvertermanager);
        EntityFireworkRocket.func_189656_a(dataconvertermanager);
        EntityGhast.func_189756_b(dataconvertermanager);
        EntityGiantZombie.func_189765_b(dataconvertermanager);
        EntityGuardian.func_189766_b(dataconvertermanager);
        EntityHorse.func_189803_b(dataconvertermanager);
        EntityHusk.func_190740_b(dataconvertermanager);
        EntityItem.func_189742_a(dataconvertermanager);
        EntityItemFrame.func_189738_a(dataconvertermanager);
        EntityLargeFireball.func_189744_a(dataconvertermanager);
        EntityMagmaCube.func_189759_b(dataconvertermanager);
        EntityMinecartChest.func_189681_a(dataconvertermanager);
        EntityMinecartCommandBlock.func_189670_a(dataconvertermanager);
        EntityMinecartFurnace.func_189671_a(dataconvertermanager);
        EntityMinecartHopper.func_189682_a(dataconvertermanager);
        EntityMinecartEmpty.func_189673_a(dataconvertermanager);
        EntityMinecartMobSpawner.func_189672_a(dataconvertermanager);
        EntityMinecartTNT.func_189674_a(dataconvertermanager);
        EntityMule.func_190700_b(dataconvertermanager);
        EntityMooshroom.func_189791_c(dataconvertermanager);
        EntityOcelot.func_189787_b(dataconvertermanager);
        EntityPig.func_189792_b(dataconvertermanager);
        EntityPigZombie.func_189781_b(dataconvertermanager);
        EntityRabbit.func_189801_b(dataconvertermanager);
        EntitySheep.func_189802_b(dataconvertermanager);
        EntityShulker.func_189757_b(dataconvertermanager);
        EntitySilverfish.func_189767_b(dataconvertermanager);
        EntitySkeleton.func_189772_b(dataconvertermanager);
        EntitySkeletonHorse.func_190692_b(dataconvertermanager);
        EntitySlime.func_189758_c(dataconvertermanager);
        EntitySmallFireball.func_189745_a(dataconvertermanager);
        EntitySnowman.func_189783_b(dataconvertermanager);
        EntitySnowball.func_189662_a(dataconvertermanager);
        EntitySpectralArrow.func_189659_b(dataconvertermanager);
        EntitySpider.func_189774_d(dataconvertermanager);
        EntitySquid.func_189804_b(dataconvertermanager);
        EntityStray.func_190728_b(dataconvertermanager);
        EntityEgg.func_189664_a(dataconvertermanager);
        EntityEnderPearl.func_189663_a(dataconvertermanager);
        EntityExpBottle.func_189666_a(dataconvertermanager);
        EntityPotion.func_189665_a(dataconvertermanager);
        EntityTippedArrow.func_189660_b(dataconvertermanager);
        EntityVex.func_190663_b(dataconvertermanager);
        EntityVillager.func_189785_b(dataconvertermanager);
        EntityIronGolem.func_189784_b(dataconvertermanager);
        EntityVindicator.func_190641_b(dataconvertermanager);
        EntityWitch.func_189776_b(dataconvertermanager);
        EntityWither.func_189782_b(dataconvertermanager);
        EntityWitherSkeleton.func_190729_b(dataconvertermanager);
        EntityWitherSkull.func_189746_a(dataconvertermanager);
        EntityWolf.func_189788_b(dataconvertermanager);
        EntityZombie.func_189779_d(dataconvertermanager);
        EntityZombieHorse.func_190693_b(dataconvertermanager);
        EntityZombieVillager.func_190737_b(dataconvertermanager);
        TileEntityPiston.func_189685_a(dataconvertermanager);
        TileEntityFlowerPot.func_189699_a(dataconvertermanager);
        TileEntityFurnace.func_189676_a(dataconvertermanager);
        TileEntityChest.func_189677_a(dataconvertermanager);
        TileEntityDispenser.func_189678_a(dataconvertermanager);
        TileEntityDropper.func_189679_b(dataconvertermanager);
        TileEntityBrewingStand.func_189675_a(dataconvertermanager);
        TileEntityHopper.func_189683_a(dataconvertermanager);
        BlockJukebox.func_189873_a(dataconvertermanager);
        TileEntityMobSpawner.func_189684_a(dataconvertermanager);
        TileEntityShulkerBox.func_190593_a(dataconvertermanager);
        func_188276_a(dataconvertermanager);
        return dataconvertermanager;
    }

    public static NBTTagCompound func_188277_a(IDataFixer dataconverter, NBTTagCompound nbttagcompound, int i, String s) {
        if (nbttagcompound.func_150297_b(s, 10)) {
            nbttagcompound.func_74782_a(s, dataconverter.func_188251_a(FixTypes.ITEM_INSTANCE, nbttagcompound.func_74775_l(s), i));
        }

        return nbttagcompound;
    }

    public static NBTTagCompound func_188278_b(IDataFixer dataconverter, NBTTagCompound nbttagcompound, int i, String s) {
        if (nbttagcompound.func_150297_b(s, 9)) {
            NBTTagList nbttaglist = nbttagcompound.func_150295_c(s, 10);

            for (int j = 0; j < nbttaglist.func_74745_c(); ++j) {
                nbttaglist.func_150304_a(j, dataconverter.func_188251_a(FixTypes.ITEM_INSTANCE, nbttaglist.func_150305_b(j), i));
            }
        }

        return nbttagcompound;
    }
}
